# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build/release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install

      - name: build extension
        run: npm run build

  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install

      - name: build extension
        run: npm run complete

      - name: Get VERSION
        run: |
          echo "VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: 115_file_exporter_${{ env.VERSION }}
          path: artifacts/115_file_exporter-${{ env.VERSION }}.zip
